---
version: '3.6'

services:

  kafka:
    container_name: kafka
    image: kafka-test
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
    environment:
      #ADVERTISED_HOST: '127.0.0.1'
      #ADVERTISED_PORT: 9092
      #AUTO_CREATE_TOPICS: 'true'
      KAFKA_HEAP_OPTS: -Xms384M -Xmx384M
    ports:
    - 127.0.0.1:9092:9092
    #network_mode: host

